routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('products','ProductController');
});

// import
Route::get('/students/import', 'StudentController@import')->name('students.import');
Route::get('/student/template', 'StudentController@template')->name('students.import');

Route::get('/schools/import', 'SchoolController@import')->name('schools.import');
Route::get('/schools/templateSchool', 'SchoolController@template')->name('schools.import');
Route::post('/schools/importdata', 'SchoolController@importdata')->name('schools.importdata');

// schools
Route::get('/schools', 'SchoolController@index')->name('schools');
Route::get('/school/add', 'SchoolController@create')->name('school.create');
Route::post('/school/add', 'SchoolController@store')->name('school.store');
Route::get('school/{index_no}/edit', 'SchoolController@edit')->name('student.edit');
Route::post('school/{index_no}/update', 'SchoolController@update')->name('student.update');

// students
Route::get('/students', 'StudentController@index')->name('students');
Route::get('/student/add', 'StudentController@create')->name('student.create');
Route::post('/student/add', 'StudentController@store')->name('student.store');
Route::get('student/{admin}/edit', 'StudentController@edit')->name('student.edit');
Route::post('student/update', 'StudentController@create')->name('student.update');
Route::get('student/{admin}/delete', 'StudentController@delete')->name('student.delete');


// marks
Route::get('/marks', 'StudentMarksController@index')->name('marks');
Route::get('/mark/add', 'StudentMarksController@create')->name('mark.create');
Route::post('/mark/add', 'StudentMarksController@store')->name('mark.store');
Route::get('mark/{admin}/edit', 'StudentMarksController@edit')->name('mark.edit');
Route::post('mark/{admin}/update', 'StudentMarksController@update')->name('mark.update');
Route::get('mark/{admin}/delete', 'StudentMarksController@delete')->name('mark.delete');
Route::any('mark/search', 'StudentMarksController@search')->name('mark.search');
Route::any('mark/add/select', 'StudentMarksController@create')->name('student.select');

resources/views/layouts/_horizontal_menu.blade.php
<div class="row border-bottom">
    <!--<nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">-->
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="#">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
{{--            @if(Auth::guard('admin')->check() or Auth::check())--}}

            <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out"></i> {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
{{--            @endif--}}
        </ul>

    </nav>
</div>

resources/views/layouts/_left_menu.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
{{--                    <img alt="image" class="rounded-circle" src="img/profile_small.jpg"/>--}}
                    ZAIN EXAM
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">{{ Auth::user()->name ?? 'Not logged in' }}</span>
                        <span class="text-muted text-xs block">{{ Auth::user()->name ?? 'Not logged in' }} <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
{{--                        <li><a class="dropdown-item" href="profile.html">Profile</a></li>--}}
                        <li>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>


                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>

            <li>
                <a href="{{ url('marks') }}"><i class="fa fa-address-card"></i> <span class="nav-label">Results</span> </a>
            </li>
            <li>
                <a href="{{ url('schools') }}"><i class="fa fa-address-card"></i> <span class="nav-label">School</span> </a>
            </li>
            <li>
                <a href="{{ url('students') }}"><i class="fa fa-users"></i> <span class="nav-label">Students</span> </a>
            </li>
            <li>
                <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label">Admin </span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a class="nav-link" href="{{ route('users.index') }}">Manage Users</a></li>
                    <li><a class="nav-link" href="{{ route('roles.index') }}">Manage Role</a></li>
                </ul>
            </li>
        </ul>

    </div>
</nav>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto"></ul>


                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                        <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                    @else
                        <li><a class="nav-link" href="{{ route('users.index') }}">Manage Users</a></li>
                        <li><a class="nav-link" href="{{ route('roles.index') }}">Manage Role</a></li>
                        <li><a class="nav-link" href="{{ route('products.index') }}">Manage Product</a></li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>


                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>


                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>


    <main class="py-4">
        <div class="container">
            @yield('content')
        </div>
    </main>
</div>
</body>
</html>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        @section('title')
            |  Zain Exam
        @show
    </title>
    <!--page level css-->
@include('layouts.pages_css')
@yield('header_styles')
<!--end of page level css-->
</head>

<body>
<!-- Header Start -->
<header>

</header>

<!-- //Header End -->

<!-- slider / breadcrumbs section -->
@yield('top')

<!-- Content --> <!--</section>-->
<section class="content">
    <div id="wrapper">

        @include('layouts._left_menu')

        <div id="page-wrapper" class="gray-bg">
            @include('layouts._horizontal_menu')

                    @yield('content')
            @include('layouts.footer')
        </div>
    </div>
</section>

<!-- Footer Section Start -->
<footer>

</footer>
<!--
<a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" data-original-title="Return to top"
   data-toggle="tooltip" data-placement="left">
    <i class="livicon" data-name="plane-up" data-size="18" data-loop="true" data-c="#fff" data-hc="white"></i>
</a> -->



<!--global js starts-->
<!--global js end-->
<!-- begin page level js -->
@include('layouts.pages_js')
@yield('footer_scripts')
<!-- end page level js -->

</body>

</html>

resources/views/layouts/footer.blade.php
<div class="footer">
    <div class="pull-right">
        {{--10GB of <strong>250GB</strong> Free.--}}
        <strong>Copyright</strong> zainexam &copy; 2020
    </div>
    <div>
        {{--<strong>Copyright</strong> mlipia &copy; 2019-2020--}}
    </div>
</div>

resources/views/layouts/pages_css.blade.php
<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('font-awesome/css/font-awesome.css') }}">
<link rel="stylesheet" href="{{ asset('css/animate.css') }}">
<link rel="stylesheet" href="{{ asset('css/style.css') }}">
<script type="text/javascript" src="{{ asset('js/jquery-3.1.1.min.js') }}"></script>

<meta name="_token" content="{{ csrf_token() }}">

resources/views/layouts/pages_js.blade.php
<!-- Mainly scripts -->
<script type="text/javascript" src="{{ asset('js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/metisMenu/jquery.metisMenu.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>

<!-- Custom and plugin javascript -->
<script type="text/javascript" src="{{ asset('js/inspinia.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/pace/pace.min.js') }}"></script>